# Generated by Django 4.2.4 on 2023-08-16 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_teammembers_taskassignments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskAssignments',
            new_name='TaskAssignment',
        ),
        migrations.RenameModel(
            old_name='TeamMembers',
            new_name='TeamMember',
        ),
    ]
