# Generated by Django 4.2.4 on 2023-08-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_taskassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[(1, 'Manager'), (2, 'Team leader'), (3, 'Team memeber')], default='Manager', max_length=10),
        ),
    ]
