# Generated by Django 4.2.4 on 2023-08-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_role_alter_taskassignment_member_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(default='1', verbose_name=(('Created', 'Created'), ('Assigned', 'Assigned'), ('In Progrss', 'In Progrss'), ('Under Review', 'Under Review'), ('Done', 'Done'))),
        ),
    ]
