# Generated by Django 4.2.4 on 2023-08-17 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_task_team_id_alter_team_team_lead'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team_id', 'member_id')},
        ),
    ]
