# Generated by Django 4.2.4 on 2023-08-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_teammember_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Team leader', 'Team leader'), ('Team member', 'Team member')], default='Manager', max_length=100),
        ),
    ]
