# Generated by Django 4.2.4 on 2023-08-22 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignment',
            name='member_id',
            field=models.ForeignKey(limit_choices_to={'role': 'Team member'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='member_id',
            field=models.ForeignKey(limit_choices_to={'role': 'Team member'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
